<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Kategori baru berdasarkan durasi
        $cat1H   = Category::firstOrCreate(['slug' => 'trip-1-hari'],      ['name' => 'Trip 1 Hari',      'sort_order' => 1, 'is_active' => true]);
        $cat2H1M = Category::firstOrCreate(['slug' => '2-hari-1-malam'],   ['name' => '2 Hari 1 Malam',   'sort_order' => 2, 'is_active' => true]);
        $cat3H2M = Category::firstOrCreate(['slug' => '3-hari-2-malam'],   ['name' => '3 Hari 2 Malam',   'sort_order' => 3, 'is_active' => true]);
        $cat4H3M = Category::firstOrCreate(['slug' => '4-hari-3-malam'],   ['name' => '4 Hari 3 Malam',   'sort_order' => 4, 'is_active' => true]);
        $cat5H4M = Category::firstOrCreate(['slug' => '5-hari-4-malam'],   ['name' => '5 Hari 4 Malam',   'sort_order' => 5, 'is_active' => true]);
        $cat6H5M = Category::firstOrCreate(['slug' => '6-hari-5-malam'],   ['name' => '6 Hari 5 Malam',   'sort_order' => 6, 'is_active' => true]);
        $catReq  = Category::firstOrCreate(['slug' => 'kategori-request'], ['name' => 'Kategori Request', 'sort_order' => 7, 'is_active' => true]);

        $products = [

            // ══════════════════════════════════════════════════════════════════
            // TRIP 1 HARI
            // ══════════════════════════════════════════════════════════════════
            [
                'category_id'       => $cat1H->id,
                'name'              => 'Private Trip Danau Toba 1 Hari',
                'slug'              => 'private-trip-danau-toba-1-hari',
                'short_description' => 'Jelajahi keindahan Danau Toba dan Pulau Samosir dalam 1 hari penuh',
                'description'       => '<p>Nikmati keindahan Danau Toba – danau vulkanik terbesar di dunia. Paket 1 hari mencakup kunjungan ke Pulau Samosir, Desa Budaya Tomok, Makam Raja Sidabutar, dan menikmati sunset di tepi danau.</p><ul><li>Kapasitas: 2–8 orang</li><li>Berangkat dari Medan atau Parapat</li><li>Armada AC + driver berpengalaman</li></ul>',
                'location_tag'      => 'Danau Toba, Samosir',
                'duration'          => '1 Hari',
                'price_min'         => 250000,
                'child_price'       => 150000,
                'price_max'         => 650000,
                'drone_price'       => 1500000,
                'drone_location'    => 'Bukit Cinta & Holbung',
                'price_display'     => 'Mulai Rp 250.000/pax',
                'rating'            => 5.0,
                'review_count'      => 42,
                'pre_order_info'    => 'PRE ORDER',
                'featured_image'    => 'https://picsum.photos/seed/danautoba1/800/600',
                'gallery_images'    => ['https://picsum.photos/seed/danautoba2/800/600','https://picsum.photos/seed/danautoba3/800/600','https://picsum.photos/seed/samosir1/800/600'],
                'pricing_details'   => [
                    ['pax' => 2, 'price_per_person' => 650000],
                    ['pax' => 3, 'price_per_person' => 500000],
                    ['pax' => 4, 'price_per_person' => 400000],
                    ['pax' => 5, 'price_per_person' => 350000],
                    ['pax' => 6, 'price_per_person' => 300000],
                    ['pax' => 7, 'price_per_person' => 280000],
                    ['pax' => 8, 'price_per_person' => 250000],
                ],
                'itinerary'         => [['name' => 'RUTE PARAPAT – SAMOSIR', 'schedule' => [
                    ['time' => '07.00', 'activity' => 'Jemput dari hotel / titik kumpul'],
                    ['time' => '07.00–09.30', 'activity' => 'Perjalanan menuju Parapat'],
                    ['time' => '09.30–10.00', 'activity' => 'Naik kapal ferry ke Pulau Samosir'],
                    ['time' => '10.00–12.00', 'activity' => 'Desa Tomok & Makam Raja Sidabutar'],
                    ['time' => '12.00–13.00', 'activity' => 'Makan siang (tidak termasuk)'],
                    ['time' => '13.00–15.00', 'activity' => 'Pantai Pasir Putih Parbaba'],
                    ['time' => '15.00–16.00', 'activity' => 'Huta Bolon Simanindo (Museum Batak)'],
                    ['time' => '16.30', 'activity' => 'Kembali ke Parapat, perjalanan pulang'],
                    ['time' => '19.00', 'activity' => 'Tiba di Medan / FINISH'],
                ]]],
                'trip_options'      => [['name' => 'Berangkat dari Medan'], ['name' => 'Berangkat dari Parapat']],
                'includes'          => ['Mobil AC', 'Driver berpengalaman', 'BBM', 'Parkir', 'Tiket ferry'],
                'excludes'          => ['Tiket masuk wisata', 'Makan & minum', 'Penginapan', 'Pengeluaran pribadi'],
                'notes'             => 'Harga per orang. Konfirmasi H-1 sebelum keberangkatan.',
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 1,
            ],
            [
                'category_id'       => $cat1H->id,
                'name'              => 'City Tour Medan 1 Hari',
                'slug'              => 'city-tour-medan-1hari',
                'short_description' => 'Wisata kota Medan lengkap – Istana Maimun, Masjid Raya, kuliner legendaris',
                'description'       => '<p>Jelajahi keindahan kota Medan dalam satu hari penuh. Kunjungi Istana Maimun, Masjid Raya Al-Mashun, Tjong A Fie Mansion, dan nikmati kuliner khas Sumatera Utara.</p>',
                'location_tag'      => 'Kota Medan',
                'duration'          => '1 Hari',
                'price_min'         => 150000,
                'child_price'       => 100000,
                'price_max'         => 400000,
                'drone_price'       => 1500000,
                'price_display'     => 'Mulai Rp 150.000/pax',
                'rating'            => 4.9,
                'review_count'      => 58,
                'featured_image'    => 'https://picsum.photos/seed/medancity/800/600',
                'gallery_images'    => ['https://picsum.photos/seed/istana-maimun/800/600','https://picsum.photos/seed/masjid-raya-medan/800/600'],
                'pricing_details'   => [
                    ['pax' => 2, 'price_per_person' => 400000],
                    ['pax' => 3, 'price_per_person' => 300000],
                    ['pax' => 4, 'price_per_person' => 250000],
                    ['pax' => 6, 'price_per_person' => 200000],
                    ['pax' => 8, 'price_per_person' => 150000],
                ],
                'itinerary'         => [['name' => 'CITY TOUR MEDAN CLASSIC', 'schedule' => [
                    ['time' => '08.00', 'activity' => 'Jemput dari hotel'],
                    ['time' => '08.30–10.00', 'activity' => 'Istana Maimun'],
                    ['time' => '10.00–11.30', 'activity' => 'Masjid Raya Al-Mashun'],
                    ['time' => '11.30–13.00', 'activity' => 'Tjong A Fie Mansion + Makan Siang'],
                    ['time' => '14.00–15.30', 'activity' => 'Pasar Rame & Oleh-oleh'],
                    ['time' => '15.30–17.00', 'activity' => 'Merdeka Walk'],
                    ['time' => '17.00', 'activity' => 'Antar ke hotel / FINISH'],
                ]]],
                'includes'          => ['Mobil AC', 'Driver', 'BBM', 'Parkir'],
                'excludes'          => ['Tiket masuk', 'Makan & minum', 'Pengeluaran pribadi'],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 2,
            ],
            [
                'category_id'       => $cat1H->id,
                'name'              => 'Wisata Berastagi & Gunung Sibayak 1 Hari',
                'slug'              => 'wisata-berastagi-gunung-sibayak',
                'short_description' => 'Mendaki Gunung Sibayak dan menikmati sejuknya Berastagi',
                'description'       => '<p>Berastagi adalah kota wisata di dataran tinggi Karo, dikelilingi oleh gunung berapi aktif: Sibayak dan Sinabung. Udara sejuk, pemandangan indah, dan buah-buahan segar menanti Anda.</p>',
                'location_tag'      => 'Berastagi, Karo',
                'duration'          => '1 Hari',
                'price_min'         => 200000,
                'child_price'       => 120000,
                'price_max'         => 500000,
                'drone_price'       => 1500000,
                'price_display'     => 'Mulai Rp 200.000/pax',
                'rating'            => 5.0,
                'review_count'      => 33,
                'featured_image'    => 'https://picsum.photos/seed/berastagi/800/600',
                'gallery_images'    => ['https://picsum.photos/seed/sibayak1/800/600','https://picsum.photos/seed/berastagi2/800/600'],
                'pricing_details'   => [
                    ['pax' => 2, 'price_per_person' => 500000],
                    ['pax' => 3, 'price_per_person' => 400000],
                    ['pax' => 4, 'price_per_person' => 300000],
                    ['pax' => 6, 'price_per_person' => 250000],
                    ['pax' => 8, 'price_per_person' => 200000],
                ],
                'includes'          => ['Mobil AC', 'Driver', 'BBM', 'Parkir'],
                'excludes'          => ['Tiket masuk', 'Makan', 'Perlengkapan mendaki', 'Guide lokal'],
                'is_featured'       => false,
                'is_active'         => true,
                'sort_order'        => 3,
            ],

            // ══════════════════════════════════════════════════════════════════
            // 2 HARI 1 MALAM
            // ══════════════════════════════════════════════════════════════════
            [
                'category_id'       => $cat2H1M->id,
                'name'              => 'Paket Danau Toba 2 Hari 1 Malam',
                'slug'              => 'danau-toba-2hari-1malam',
                'short_description' => 'Paket lengkap 2H1M dengan penginapan di tepi Danau Toba',
                'description'       => '<p>Paket 2 hari 1 malam di Danau Toba dengan penginapan yang menghadap langsung ke danau. Cocok untuk keluarga maupun pasangan.</p>',
                'location_tag'      => 'Danau Toba, Samosir',
                'duration'          => '2 Hari 1 Malam',
                'price_min'         => 500000,
                'child_price'       => 300000,
                'price_max'         => 1500000,
                'drone_price'       => 1500000,
                'drone_location'    => 'Bukit Cinta & Holbung',
                'price_display'     => 'Mulai Rp 500.000/pax',
                'rating'            => 5.0,
                'review_count'      => 27,
                'pre_order_info'    => 'PRE ORDER',
                'featured_image'    => 'https://picsum.photos/seed/toba2hari/800/600',
                'gallery_images'    => ['https://picsum.photos/seed/toba2h1/800/600','https://picsum.photos/seed/toba2h2/800/600'],
                'pricing_details'   => [
                    ['pax' => 2, 'price_per_person' => 1500000],
                    ['pax' => 3, 'price_per_person' => 1100000],
                    ['pax' => 4, 'price_per_person' => 900000],
                    ['pax' => 5, 'price_per_person' => 750000],
                    ['pax' => 6, 'price_per_person' => 650000],
                    ['pax' => 8, 'price_per_person' => 500000],
                ],
                'itinerary'         => [
                    ['name' => 'HARI 1 – MEDAN KE DANAU TOBA', 'schedule' => [
                        ['time' => '07.00', 'activity' => 'Jemput dari hotel di Medan'],
                        ['time' => '07.00–11.00', 'activity' => 'Perjalanan Medan – Parapat (via Berastagi)'],
                        ['time' => '11.00–11.30', 'activity' => 'Ferry ke Pulau Samosir'],
                        ['time' => '12.00–13.00', 'activity' => 'Makan siang di Tuktuk'],
                        ['time' => '13.00–17.00', 'activity' => 'Desa Tomok, Pantai Parbaba, Batu Kursi Raja'],
                        ['time' => '17.00', 'activity' => 'Check-in hotel / Free time'],
                    ]],
                    ['name' => 'HARI 2 – SAMOSIR & KEMBALI', 'schedule' => [
                        ['time' => '08.00', 'activity' => 'Sarapan & Check-out'],
                        ['time' => '09.00–12.00', 'activity' => 'Museum Huta Bolon, Air Terjun Efrata'],
                        ['time' => '12.30', 'activity' => 'Ferry kembali ke Parapat'],
                        ['time' => '13.00–16.30', 'activity' => 'Perjalanan pulang ke Medan'],
                        ['time' => '17.00', 'activity' => 'Tiba di Medan / FINISH'],
                    ]],
                ],
                'includes'          => ['Mobil AC', 'Driver', 'BBM', 'Parkir', 'Penginapan 1 malam', 'Tiket ferry'],
                'excludes'          => ['Tiket masuk wisata', 'Makan & minum', 'Pengeluaran pribadi'],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 4,
            ],
            [
                'category_id'       => $cat2H1M->id,
                'name'              => 'Paket Berastagi-Sipiso piso 2 Hari 1 Malam',
                'slug'              => 'berastagi-sipiso-piso-2h1m',
                'short_description' => 'Eksplorasi Berastagi, Air Terjun Sipiso-piso dan pemandian air panas Lau Sidebuk-debuk',
                'description'       => '<p>Paket wisata ke Tanah Karo selama 2 hari 1 malam. Kunjungi Air Terjun Sipiso-piso yang spektakuler, mendaki Gunung Sibayak, menikmati pemandian air panas alami, dan wisata buah di Berastagi.</p>',
                'location_tag'      => 'Berastagi, Sipiso-piso',
                'duration'          => '2 Hari 1 Malam',
                'price_min'         => 450000,
                'child_price'       => 250000,
                'price_max'         => 1200000,
                'drone_price'       => 1500000,
                'price_display'     => 'Mulai Rp 450.000/pax',
                'rating'            => 4.8,
                'review_count'      => 19,
                'featured_image'    => 'https://picsum.photos/seed/sipiso-piso/800/600',
                'gallery_images'    => ['https://picsum.photos/seed/berastagi-night/800/600','https://picsum.photos/seed/karo-highland/800/600'],
                'pricing_details'   => [
                    ['pax' => 2, 'price_per_person' => 1200000],
                    ['pax' => 3, 'price_per_person' => 900000],
                    ['pax' => 4, 'price_per_person' => 700000],
                    ['pax' => 6, 'price_per_person' => 550000],
                    ['pax' => 8, 'price_per_person' => 450000],
                ],
                'includes'          => ['Mobil AC', 'Driver', 'BBM', 'Parkir', 'Penginapan 1 malam'],
                'excludes'          => ['Tiket masuk wisata', 'Makan & minum', 'Perlengkapan mendaki'],
                'is_featured'       => false,
                'is_active'         => true,
                'sort_order'        => 5,
            ],

            // ══════════════════════════════════════════════════════════════════
            // 3 HARI 2 MALAM
            // ══════════════════════════════════════════════════════════════════
            [
                'category_id'       => $cat3H2M->id,
                'name'              => 'Paket Danau Toba Lengkap 3 Hari 2 Malam',
                'slug'              => 'danau-toba-lengkap-3h2m',
                'short_description' => 'Eksplorasi total Danau Toba, Samosir, Berastagi dalam 3 hari 2 malam',
                'description'       => '<p>Paket perjalanan 3 hari 2 malam menjelajahi keindahan Danau Toba secara menyeluruh. Mengunjungi Pulau Samosir, Berastagi, Sipiso-piso, dan berbagai destinasi ikonik Sumatera Utara.</p>',
                'location_tag'      => 'Danau Toba, Berastagi, Samosir',
                'duration'          => '3 Hari 2 Malam',
                'price_min'         => 900000,
                'child_price'       => 500000,
                'price_max'         => 2500000,
                'drone_price'       => 1500000,
                'drone_location'    => 'Bukit Cinta, Holbung & Sipiso-piso',
                'price_display'     => 'Mulai Rp 900.000/pax',
                'rating'            => 5.0,
                'review_count'      => 35,
                'pre_order_info'    => 'PRE ORDER',
                'featured_image'    => 'https://picsum.photos/seed/toba3hari/800/600',
                'gallery_images'    => ['https://picsum.photos/seed/toba-morning/800/600','https://picsum.photos/seed/samosir-sunset/800/600','https://picsum.photos/seed/sipiso-panorama/800/600'],
                'pricing_details'   => [
                    ['pax' => 2, 'price_per_person' => 2500000],
                    ['pax' => 3, 'price_per_person' => 1800000],
                    ['pax' => 4, 'price_per_person' => 1400000],
                    ['pax' => 5, 'price_per_person' => 1200000],
                    ['pax' => 6, 'price_per_person' => 1050000],
                    ['pax' => 8, 'price_per_person' => 900000],
                ],
                'itinerary'         => [
                    ['name' => 'HARI 1 – MEDAN – BERASTAGI', 'schedule' => [
                        ['time' => '07.00', 'activity' => 'Jemput dari hotel/bandara'],
                        ['time' => '07.00–10.00', 'activity' => 'Perjalanan ke Berastagi'],
                        ['time' => '10.00–12.00', 'activity' => 'Gunung Sibayak / Pasar Buah Berastagi'],
                        ['time' => '12.00–13.00', 'activity' => 'Makan siang'],
                        ['time' => '13.00–15.00', 'activity' => 'Air Terjun Sipiso-piso'],
                        ['time' => '15.00–17.00', 'activity' => 'Perjalanan ke Parapat / Check-in hotel'],
                    ]],
                    ['name' => 'HARI 2 – SAMOSIR ISLAND', 'schedule' => [
                        ['time' => '08.00', 'activity' => 'Sarapan & Ferry ke Samosir'],
                        ['time' => '09.00–12.00', 'activity' => 'Desa Tomok, Batu Kursi Raja, Museum Batak'],
                        ['time' => '12.00–13.00', 'activity' => 'Makan siang di Tuktuk'],
                        ['time' => '13.00–16.00', 'activity' => 'Pantai Parbaba, Bukit Holbung'],
                        ['time' => '16.00', 'activity' => 'Kembali ke hotel / Free time'],
                    ]],
                    ['name' => 'HARI 3 – KEMBALI KE MEDAN', 'schedule' => [
                        ['time' => '08.00', 'activity' => 'Sarapan & Check-out'],
                        ['time' => '09.00–10.00', 'activity' => 'Air Terjun Efrata / Spot foto'],
                        ['time' => '10.30', 'activity' => 'Ferry ke Parapat'],
                        ['time' => '11.00–15.00', 'activity' => 'Perjalanan pulang ke Medan'],
                        ['time' => '15.00', 'activity' => 'Tiba di Medan / Antar ke bandara'],
                    ]],
                ],
                'includes'          => ['Mobil AC', 'Driver', 'BBM', 'Parkir', 'Penginapan 2 malam', 'Tiket ferry'],
                'excludes'          => ['Tiket masuk wisata', 'Makan & minum', 'Tiket pesawat', 'Pengeluaran pribadi'],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 6,
            ],
            [
                'category_id'       => $cat3H2M->id,
                'name'              => 'Trip Pulau Nias 3 Hari 2 Malam',
                'slug'              => 'trip-pulau-nias-3hari',
                'short_description' => 'Jelajahi keajaiban budaya dan pantai eksotis Pulau Nias',
                'description'       => '<p>Pulau Nias terkenal dengan tradisi lompat batu (Hombo Batu), desa tradisional Bawömataluo, dan ombak surfing kelas dunia di Lagundri. Paket 3 hari ini dirancang untuk menikmati semua keistimewaan Nias.</p>',
                'location_tag'      => 'Pulau Nias',
                'duration'          => '3 Hari 2 Malam',
                'price_min'         => 1200000,
                'child_price'       => 700000,
                'price_max'         => 3500000,
                'drone_price'       => 1500000,
                'price_display'     => 'Mulai Rp 1.200.000/pax',
                'rating'            => 5.0,
                'review_count'      => 11,
                'pre_order_info'    => 'PRE ORDER',
                'featured_image'    => 'https://picsum.photos/seed/nias-beach/800/600',
                'gallery_images'    => ['https://picsum.photos/seed/nias-hombo/800/600','https://picsum.photos/seed/nias-surf/800/600'],
                'pricing_details'   => [
                    ['pax' => 2, 'price_per_person' => 3500000],
                    ['pax' => 3, 'price_per_person' => 2800000],
                    ['pax' => 4, 'price_per_person' => 2200000],
                    ['pax' => 6, 'price_per_person' => 1600000],
                    ['pax' => 8, 'price_per_person' => 1200000],
                ],
                'includes'          => ['Tiket pesawat Medan–Nias PP', 'Penginapan 2 malam', 'Mobil AC', 'Driver lokal', 'Guide'],
                'excludes'          => ['Makan & minum', 'Pengeluaran pribadi', 'Biaya surfing'],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 7,
            ],

            // ══════════════════════════════════════════════════════════════════
            // 4 HARI 3 MALAM
            // ══════════════════════════════════════════════════════════════════
            [
                'category_id'       => $cat4H3M->id,
                'name'              => 'Paket Wisata Sumut Komplit 4 Hari 3 Malam',
                'slug'              => 'wisata-sumut-komplit-4h3m',
                'short_description' => 'Eksplorasi Medan, Berastagi, Danau Toba & Samosir selama 4 hari 3 malam',
                'description'       => '<p>Paket wisata paling populer! 4 hari 3 malam menjelajahi semua destinasi utama Sumatera Utara. Mulai dari kuliner Medan, sejuknya Berastagi, hingga keindahan Danau Toba dan budaya Batak di Samosir.</p>',
                'location_tag'      => 'Medan, Berastagi, Danau Toba',
                'duration'          => '4 Hari 3 Malam',
                'price_min'         => 1300000,
                'child_price'       => 750000,
                'price_max'         => 3500000,
                'drone_price'       => 1500000,
                'drone_location'    => 'Bukit Cinta, Holbung, Sipiso-piso',
                'price_display'     => 'Mulai Rp 1.300.000/pax',
                'rating'            => 5.0,
                'review_count'      => 48,
                'pre_order_info'    => 'PRE ORDER',
                'featured_image'    => 'https://picsum.photos/seed/sumut4hari/800/600',
                'gallery_images'    => ['https://picsum.photos/seed/medan-kuliner/800/600','https://picsum.photos/seed/sibayak-sunrise/800/600','https://picsum.photos/seed/toba-aerial/800/600'],
                'pricing_details'   => [
                    ['pax' => 2, 'price_per_person' => 3500000],
                    ['pax' => 3, 'price_per_person' => 2600000],
                    ['pax' => 4, 'price_per_person' => 2100000],
                    ['pax' => 5, 'price_per_person' => 1800000],
                    ['pax' => 6, 'price_per_person' => 1550000],
                    ['pax' => 8, 'price_per_person' => 1300000],
                ],
                'itinerary'         => [
                    ['name' => 'HARI 1 – MEDAN CITY TOUR', 'schedule' => [
                        ['time' => '09.00', 'activity' => 'Jemput dari bandara/hotel'],
                        ['time' => '10.00–12.00', 'activity' => 'Istana Maimun & Masjid Raya'],
                        ['time' => '12.00–13.00', 'activity' => 'Makan siang kuliner Medan'],
                        ['time' => '14.00–17.00', 'activity' => 'Tjong A Fie, Merdeka Walk, oleh-oleh'],
                        ['time' => '17.00', 'activity' => 'Check-in hotel Medan'],
                    ]],
                    ['name' => 'HARI 2 – BERASTAGI', 'schedule' => [
                        ['time' => '07.00', 'activity' => 'Perjalanan ke Berastagi'],
                        ['time' => '09.30–11.00', 'activity' => 'Gunung Sibayak / Pemandian air panas'],
                        ['time' => '11.00–12.00', 'activity' => 'Pasar Buah Berastagi'],
                        ['time' => '12.00–13.00', 'activity' => 'Makan siang'],
                        ['time' => '13.00–15.00', 'activity' => 'Sipiso-piso Waterfall'],
                        ['time' => '15.00–17.00', 'activity' => 'Perjalanan ke Parapat / Check-in hotel'],
                    ]],
                    ['name' => 'HARI 3 – SAMOSIR ISLAND', 'schedule' => [
                        ['time' => '08.00', 'activity' => 'Ferry ke Samosir'],
                        ['time' => '09.00–12.00', 'activity' => 'Tomok, Batu Kursi Raja, Museum Batak'],
                        ['time' => '12.00–13.00', 'activity' => 'Makan siang'],
                        ['time' => '13.00–17.00', 'activity' => 'Pantai Parbaba, Bukit Holbung, sunset'],
                        ['time' => '17.00', 'activity' => 'Kembali ke hotel'],
                    ]],
                    ['name' => 'HARI 4 – KEMBALI KE MEDAN', 'schedule' => [
                        ['time' => '08.00', 'activity' => 'Check-out & Ferry ke Parapat'],
                        ['time' => '09.00–13.00', 'activity' => 'Perjalanan ke Medan'],
                        ['time' => '13.00', 'activity' => 'Tiba di Medan / Antar ke bandara'],
                    ]],
                ],
                'includes'          => ['Mobil AC', 'Driver berpengalaman', 'BBM', 'Parkir', 'Penginapan 3 malam', 'Tiket ferry'],
                'excludes'          => ['Tiket masuk wisata', 'Makan & minum', 'Tiket pesawat', 'Pengeluaran pribadi'],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 8,
            ],
            [
                'category_id'       => $cat4H3M->id,
                'name'              => 'Honeymoon Package Danau Toba 4 Hari 3 Malam',
                'slug'              => 'honeymoon-danau-toba-4h3m',
                'short_description' => 'Paket bulan madu romantis di Danau Toba dengan villa tepi danau',
                'description'       => '<p>Rayakan momen spesial bersama pasangan di Danau Toba. Paket honeymoon eksklusif ini mencakup villa romantis dengan pemandangan danau, dinner candle light, island hopping di Samosir, dan dokumentasi foto.</p>',
                'location_tag'      => 'Danau Toba, Samosir',
                'duration'          => '4 Hari 3 Malam',
                'price_min'         => 4500000,
                'child_price'       => 0,
                'price_max'         => 4500000,
                'drone_price'       => 1500000,
                'drone_location'    => 'Bukit Cinta & spot romantis',
                'price_display'     => 'Rp 4.500.000 / couple',
                'rating'            => 5.0,
                'review_count'      => 8,
                'featured_image'    => 'https://picsum.photos/seed/honeymoon-toba/800/600',
                'gallery_images'    => ['https://picsum.photos/seed/honeymoon1/800/600','https://picsum.photos/seed/honeymoon2/800/600','https://picsum.photos/seed/honeymoon3/800/600'],
                'pricing_details'   => [
                    ['pax' => 2, 'price_per_person' => 4500000],
                ],
                'includes'          => ['Villa tepi danau 3 malam', 'Romantic dinner', 'Mobil AC', 'Driver', 'Tiket ferry', 'Welcome fruit', 'Dokumentasi foto 1 sesi'],
                'excludes'          => ['Tiket pesawat', 'Makan (selain romantic dinner)', 'Pengeluaran pribadi'],
                'notes'             => 'Harga per couple. Pemesanan minimal 7 hari sebelum keberangkatan.',
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 9,
            ],

            // ══════════════════════════════════════════════════════════════════
            // 5 HARI 4 MALAM
            // ══════════════════════════════════════════════════════════════════
            [
                'category_id'       => $cat5H4M->id,
                'name'              => 'Grand Tour Sumatera Utara 5 Hari 4 Malam',
                'slug'              => 'grand-tour-sumut-5h4m',
                'short_description' => 'Perjalanan lengkap Medan-Berastagi-Toba-Samosir-Bukit Lawang dalam 5 hari',
                'description'       => '<p>Paket grand tour terlengkap menjelajahi Sumatera Utara. Dari Medan menuju Berastagi, Danau Toba, Samosir, hingga Bukit Lawang untuk melihat orangutan di habitat aslinya. 5 hari penuh petualangan tanpa batas.</p>',
                'location_tag'      => 'Medan, Berastagi, Toba, Bukit Lawang',
                'duration'          => '5 Hari 4 Malam',
                'price_min'         => 1800000,
                'child_price'       => 1000000,
                'price_max'         => 4500000,
                'drone_price'       => 1500000,
                'drone_location'    => 'Multi lokasi',
                'price_display'     => 'Mulai Rp 1.800.000/pax',
                'rating'            => 5.0,
                'review_count'      => 22,
                'pre_order_info'    => 'PRE ORDER',
                'featured_image'    => 'https://picsum.photos/seed/grandtour-sumut/800/600',
                'gallery_images'    => ['https://picsum.photos/seed/bukit-lawang/800/600','https://picsum.photos/seed/orangutan/800/600','https://picsum.photos/seed/toba-sunrise/800/600'],
                'pricing_details'   => [
                    ['pax' => 2, 'price_per_person' => 4500000],
                    ['pax' => 3, 'price_per_person' => 3500000],
                    ['pax' => 4, 'price_per_person' => 2800000],
                    ['pax' => 5, 'price_per_person' => 2400000],
                    ['pax' => 6, 'price_per_person' => 2100000],
                    ['pax' => 8, 'price_per_person' => 1800000],
                ],
                'includes'          => ['Mobil AC', 'Driver', 'BBM', 'Parkir', 'Penginapan 4 malam', 'Tiket ferry', 'Guide Bukit Lawang'],
                'excludes'          => ['Tiket masuk wisata', 'Makan & minum', 'Tiket pesawat', 'Pengeluaran pribadi'],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 10,
            ],

            // ══════════════════════════════════════════════════════════════════
            // 6 HARI 5 MALAM
            // ══════════════════════════════════════════════════════════════════
            [
                'category_id'       => $cat6H5M->id,
                'name'              => 'Ultimate Sumatera Utara Tour 6 Hari 5 Malam',
                'slug'              => 'ultimate-sumut-tour-6h5m',
                'short_description' => 'Paket terlengkap: Medan, Berastagi, Toba, Samosir, Bukit Lawang, Tangkahan',
                'description'       => '<p>Paket wisata ultimate 6 hari 5 malam untuk menjelajahi semua destinasi terbaik Sumatera Utara tanpa terburu-buru. Dari kota Medan, dataran tinggi Berastagi, keindahan Danau Toba, budaya Batak di Samosir, orangutan di Bukit Lawang, hingga konservasi gajah di Tangkahan.</p>',
                'location_tag'      => 'Medan, Berastagi, Toba, Bukit Lawang, Tangkahan',
                'duration'          => '6 Hari 5 Malam',
                'price_min'         => 2500000,
                'child_price'       => 1500000,
                'price_max'         => 6000000,
                'drone_price'       => 1500000,
                'drone_location'    => 'Multi lokasi',
                'price_display'     => 'Mulai Rp 2.500.000/pax',
                'rating'            => 5.0,
                'review_count'      => 14,
                'pre_order_info'    => 'PRE ORDER',
                'featured_image'    => 'https://picsum.photos/seed/ultimate-sumut/800/600',
                'gallery_images'    => ['https://picsum.photos/seed/tangkahan-elephant/800/600','https://picsum.photos/seed/toba-panorama/800/600','https://picsum.photos/seed/berastagi-aerial/800/600','https://picsum.photos/seed/medan-night/800/600'],
                'pricing_details'   => [
                    ['pax' => 2, 'price_per_person' => 6000000],
                    ['pax' => 3, 'price_per_person' => 4500000],
                    ['pax' => 4, 'price_per_person' => 3800000],
                    ['pax' => 5, 'price_per_person' => 3200000],
                    ['pax' => 6, 'price_per_person' => 2800000],
                    ['pax' => 8, 'price_per_person' => 2500000],
                ],
                'includes'          => ['Mobil AC', 'Driver berpengalaman', 'BBM', 'Parkir', 'Penginapan 5 malam', 'Tiket ferry', 'Guide Bukit Lawang & Tangkahan', 'Jungle trekking', 'Elephant washing'],
                'excludes'          => ['Tiket masuk wisata', 'Makan & minum', 'Tiket pesawat', 'Pengeluaran pribadi', 'Tip guide'],
                'is_featured'       => true,
                'is_active'         => true,
                'sort_order'        => 11,
            ],

            // ══════════════════════════════════════════════════════════════════
            // KATEGORI REQUEST
            // ══════════════════════════════════════════════════════════════════
            [
                'category_id'       => $catReq->id,
                'name'              => 'Custom Trip Sumatera Utara (Request)',
                'slug'              => 'custom-trip-sumut-request',
                'short_description' => 'Buat perjalanan sesuai keinginan Anda – destinasi, durasi, dan budget fleksibel',
                'description'       => '<p>Tidak menemukan paket yang cocok? Kami siap merancang perjalanan impian Anda! Custom trip dengan durasi, destinasi, dan akomodasi yang bisa Anda tentukan sendiri. Hubungi kami untuk konsultasi gratis.</p><ul><li>Durasi fleksibel 1–14 hari</li><li>Pilih destinasi sendiri</li><li>Budget sesuai kebutuhan</li><li>Group kecil maupun besar</li></ul>',
                'location_tag'      => 'Sumatera Utara',
                'duration'          => 'Fleksibel',
                'price_min'         => 200000,
                'child_price'       => 100000,
                'price_max'         => 10000000,
                'price_display'     => 'Hubungi untuk penawaran',
                'rating'            => 5.0,
                'review_count'      => 15,
                'featured_image'    => 'https://picsum.photos/seed/custom-trip/800/600',
                'gallery_images'    => ['https://picsum.photos/seed/custom1/800/600','https://picsum.photos/seed/custom2/800/600'],
                'includes'          => ['Mobil AC', 'Driver', 'BBM', 'Parkir', 'Itinerary custom'],
                'excludes'          => ['Tergantung paket yang dipilih'],
                'notes'             => 'Hubungi kami via WhatsApp untuk konsultasi dan penawaran harga custom.',
                'is_featured'       => false,
                'is_active'         => true,
                'sort_order'        => 12,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['slug' => $product['slug']],
                $product
            );
        }
    }
}
